CREATE TABLE IF NOT EXISTS audio_job_metrics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audio_job_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  metric_group_key VARCHAR(80) NOT NULL,
  metric_group_label VARCHAR(160) NOT NULL,
  metric_key VARCHAR(120) NOT NULL,
  metric_label VARCHAR(190) NOT NULL,
  metric_value_text TEXT NULL,
  metric_value_number DOUBLE NULL,
  unit VARCHAR(40) NOT NULL DEFAULT '',
  source_path VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NULL,
  captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_audio_job_metrics_job_key (audio_job_id, metric_key),
  KEY idx_audio_job_metrics_user_time (user_id, captured_at),
  KEY idx_audio_job_metrics_user_key_time (user_id, metric_key, captured_at),
  KEY idx_audio_job_metrics_product_key_time (product_id, metric_key, captured_at),
  CONSTRAINT fk_audio_job_metrics_job FOREIGN KEY (audio_job_id) REFERENCES audio_jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_audio_job_metrics_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_audio_job_metrics_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
