CREATE TABLE IF NOT EXISTS analysis_engines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description VARCHAR(255) NULL,
  endpoint_url VARCHAR(255) NULL,
  output_contract_version VARCHAR(40) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_analysis_engines_product_code (product_id, code),
  CONSTRAINT fk_analysis_engines_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analysis_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  analysis_engine_id BIGINT UNSIGNED NULL,
  source_job_type VARCHAR(80) NULL,
  source_job_id BIGINT UNSIGNED NULL,
  input_title VARCHAR(190) NOT NULL DEFAULT '',
  input_description VARCHAR(255) NOT NULL DEFAULT '',
  input_filename VARCHAR(255) NULL,
  input_mime_type VARCHAR(120) NULL,
  input_size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  request_payload_json JSON NULL,
  response_payload_json JSON NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  processed_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_analysis_jobs_source (source_job_type, source_job_id),
  KEY idx_analysis_jobs_user_time (user_id, created_at),
  KEY idx_analysis_jobs_product_time (product_id, created_at),
  KEY idx_analysis_jobs_engine_time (analysis_engine_id, created_at),
  KEY idx_analysis_jobs_status (status),
  CONSTRAINT fk_analysis_jobs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_jobs_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_jobs_engine FOREIGN KEY (analysis_engine_id) REFERENCES analysis_engines(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analysis_metrics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  analysis_job_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  metric_group_key VARCHAR(80) NOT NULL,
  metric_group_label VARCHAR(160) NOT NULL,
  metric_key VARCHAR(120) NOT NULL,
  metric_label VARCHAR(190) NOT NULL,
  metric_value_text TEXT NULL,
  metric_value_number DOUBLE NULL,
  unit VARCHAR(40) NOT NULL DEFAULT '',
  source_path VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NULL,
  captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_analysis_metrics_job_key (analysis_job_id, metric_key),
  KEY idx_analysis_metrics_user_time (user_id, captured_at),
  KEY idx_analysis_metrics_product_key_time (product_id, metric_key, captured_at),
  CONSTRAINT fk_analysis_metrics_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_metrics_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_metrics_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analysis_feature_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  analysis_job_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  features_json JSON NOT NULL,
  numeric_features_json JSON NULL,
  feature_labels_json JSON NULL,
  feature_units_json JSON NULL,
  captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_analysis_feature_snapshots_job (analysis_job_id),
  KEY idx_analysis_feature_snapshots_user_time (user_id, captured_at),
  KEY idx_analysis_feature_snapshots_product_time (product_id, captured_at),
  CONSTRAINT fk_analysis_feature_snapshots_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_feature_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_feature_snapshots_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analysis_artifacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  analysis_job_id BIGINT UNSIGNED NOT NULL,
  artifact_type VARCHAR(80) NOT NULL,
  title VARCHAR(190) NOT NULL DEFAULT '',
  media_type VARCHAR(120) NULL,
  storage_path VARCHAR(255) NULL,
  public_url VARCHAR(255) NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_analysis_artifacts_job_type (analysis_job_id, artifact_type),
  CONSTRAINT fk_analysis_artifacts_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
